### PR TITLE
Allow new- and old-style download of models in PyTorch example

### LINKED ISSUE #53: Pytorch model download failing with 'no attribute error'
With recent commit https://github.com/gramineproject/examples/commit/2e41bcd1d1887a364fced4bd220e654c9ae41ff0 We're not able to download model for pytorch. 
It fails with below error

**python3 download-pretrained-model.py**
```
Traceback (most recent call last):
  File "download-pretrained-model.py", line 5, in <module>
    alexnet = models.alexnet(weights=models.AlexNet_Weights.IMAGENET1K_V1)
AttributeError: module 'torchvision.models' has no attribute 'AlexNet_Weights'
```

On reverting the changes back, the model is getting successfully downloaded.
 **python3 download-pretrained-model.py**
```
Downloading: "https://download.pytorch.org/models/alexnet-owt-7be5be79.pth" to /tmp/.cache/torch/hub/checkpoints/alexnet-owt-7be5be79.pth
100.0%
Pre-trained model was saved in "alexnet-pretrained.pt"
```

### PR DESCRIPTION
**Pull request by dimakuv**
Previous commit "Fix deprecation warning in PyTorch example" (https://github.com/gramineproject/examples/commit/2e41bcd1d1887a364fced4bd220e654c9ae41ff0) broke the PyTorch example on Ubuntu 18.04, CentOS 8, RHEL 8, etc. Changes in that commit work with torchvision 0.13.0+ which is available with Python 3.7+ only, however e.g. Ubuntu 18.04 comes with Python 3.6, hence torchvision 0.13.0+ cannot be installed on Ubuntu 18.04.

To allow such older OS distros, this PR allows both styles of downloading models.

Fixes #53. Closes #55.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/examples/56)

### CODE REVIEW

**Review by jkr0103 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/56#-:-NPRf8oo1BJ1IfLPJ7xj:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/56)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)
